import { Inter } from "next/font/google";
import UIProviders from "@/context/UIProviders";
import QueryProvider from "@/context/QueryProvider";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Reactor Flashcards",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
          <UIProviders>
            <QueryProvider>
              {children}
            </QueryProvider>            
          </UIProviders>
      </body>
    </html>
  );
}
