import { Inter, JetBrains_Mono } from "next/font/google";
import UIProviders from "@/context/UIProviders";
import QueryProvider from "@/context/QueryProvider";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrains_mono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Reactor Flashcards",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrains_mono.variable} antialiased`}
      >
        <QueryProvider>
          <UIProviders>{children}</UIProviders>
        </QueryProvider>
      </body>
    </html>
  );
}
